meta_product_name: "Thirst Trail"
meta_title: "Thirst Trail - YOUR POCKET COCKTAIL BUILDER"
meta_description: "YOUR POCKET COCKTAIL BUILDER"
meta_image: "logo-new-1-c.png" # should exist in `app/assets/images/`
